---
- name: add mongodb-org apt key
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: EA312927
    state: present

- name: add mongodb repository
  apt_repository:
    repo: 'deb http://repo.mongodb.org/apt/debian {{ ansible_distribution_release }}/mongodb-org/{{ mongodb_major_version }} main'
    filename: mongodb
    update_cache: yes
  when: ansible_distribution == "Debian" and ansible_distribution_major_version >= 7

- name: install mongodb-org={{ mongodb_specific_version }}
  apt:
    name: mongodb-org={{ mongodb_specific_version }}
    update_cache: yes
    force: yes

- name: deploy mongod.conf
  template: 
    src: mongod.conf.j2
    dest: /etc/mongod.conf

- name: copy mongodb keyfile
  copy:
    src: mongodb.keyfile
    dest: /etc/mongodb.keyfile
    owner: mongodb
    group: mongodb
    mode: 0400

- name: create mongodb datadir
  file:
    path: /data/mongodb
    state: directory
    owner: mongodb
    group: mongodb
